# IBaseRule （生成时的）基础规则
# 工程根路径的包名
rootPackageName: com.starbuds.server.api.channel
# 生成文件的主文件夹路径 必填 必须有结束的"/"，不填写则默认路径为 target/GENERATE/
# 生成文件的根路径
generatorRootPath: /Users/aoe/IdeaProjects/paqu/api-channel/src/main/java/com/starbuds/server/api/channel/
# 主题文件夹名称（例如：resources/themes/base 配置为 themes: base)
themes: xy/channel

# IPersistentRule （生成时的）Persistent规则
# PO(持久对象)类存储位置
poPath: $ROOT_PATH/common/pojo/db/
# PO(持久对象)类名后缀；不填写默认为空；生成后类名后缀与填写的一致
poClassNameSuffix: DO
# 生成Java文件时需要过滤掉的表名前缀（,分割）；不填写默认为空
tablePrefixFilter: tb
# Mybatis Mapper 文件路径
mapperPath: $ROOT_PATH/service/admin/dao/
# Mybatis Mapper类名后缀；不填写默认为空；生成后类名后缀与填写的一致
mapperClassNameSuffix: DAO
# Mybatis XML 文件路径
mapperXmlPath: /Users/aoe/IdeaProjects/paqu/api-channel/src/main/resources/mapper/
# Mybatis Plus Service 类存储位置
mapperServicePath: $ROOT_PATH/$MODEL_PATH/dao/service/
# Mybatis Plus Service 类后缀
mapperServiceSuffix: POService
# Mybatis Plus ServiceImpl 类存储位置
mapperServiceImplPath: $ROOT_PATH/$MODEL_PATH/dao/service/impl/
# Mybatis Plus ServiceImpl 类后缀
mapperServiceImplSuffix: POServiceImpl

# Service 生成规则
# Service 类存储位置
servicePath: $ROOT_PATH/$MODEL_PATH/service/
# Service 类后缀
serviceSuffix: Service

# web层 生成规则
# 页面查询类存储位置
pageListQOPath: $ROOT_PATH/$MODEL_PATH/web/request/qo/
# 页面查询类名后缀；不填写默认为空；生成后类名后缀与填写的一致
pageListQOClassNameSuffix: PageListQO

# VO 类存储位置
voPath: $ROOT_PATH/$MODEL_PATH/web/response/
# VO 类名后缀；不填写默认为空；生成后类名后缀与填写的一致
voClassNameSuffix: VO

# Form 表单类存储位置
formPath: $ROOT_PATH/$MODEL_PATH/web/request/form/
# Form 表单类名后缀；不填写默认为空；生成后类名后缀与填写的一致
formClassNameSuffix: Form

# 控制器类存储位置
controllerPath: $ROOT_PATH/$MODEL_PATH/web/controller/
# 控制器类名后缀；不填写默认为空；生成后类名后缀与填写的一致
controllerClassNameSuffix: Controller

# 单元测试
# 控制器测试类存储位置
controllerTestPath: $ROOT_PATH/$MODEL_PATH/web/controller/
# 控制器测试类名后缀；不填写默认为空；生成后类名后缀与填写的一致
controllerTestClassNameSuffix: ControllerTest
# 测试主机地址
hostTest: http://localhost:9990/wazhima/