# 配置信息
# 包名
packageName: com.starbuds.apichannel

# 类存储位置
filePath: /Users/aoe/IdeaProjects/paqu/api-app/src/test/java/com/starbuds/apichannel/

# 类名后缀；不填写默认为空；生成后类名后缀与填写的一致
suffix: FacadeTest

# 模板文件路径
templates: xy/media/facade_test.ftl