# 文件配置信息
# 包名
packageName: com.starbuds.server.service.media.provider

# 类存储位置
filePath: /Users/aoe/IdeaProjects/paqu/service-media/src/main/java/com/starbuds/server/service/media/provider/

# 类名后缀；不填写默认为空；生成后类名后缀与填写的一致
suffix: Provider

# 模板文件路径
templates: xy/media/provider.ftl