server:
  port: 9091
# DataSource Config
spring:
  thymeleaf:
    cache: false
  freemarker:
    cache: false    # 页面不加载缓存，修改即时生效
    prefer-file-system-access: false #不使用文件系统优先，而使用classpath下的资源文件优先，解决打jar包运行后，出现的异常问题
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    # dev-db-wazhima db-starbuds
    url: jdbc:mysql://localhost:3306/mysql-test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root

mybatis:
  mapperLocations: classpath:mapper/**/*.xml