# 配置信息
# 包名
packageName: com.starbuds.server.api.channel.common.pojo.form

# 类存储位置
filePath: /Users/aoe/IdeaProjects/paqu/api-channel/src/main/java/com/starbuds/server/api/channel/common/pojo/form/

# 类名后缀；不填写默认为空；生成后类名后缀与填写的一致
suffix: Form

# 模板文件路径
templates: xy/finance/form.ftl