# 自定义变量

# 模块名称
model: rtc
# 包名前缀
packagePrefix: com.starbuds.server.service.${model}

# 所有工程的根目录
allRootPaht: /Users/aoe/IdeaProjects/paqu/fastFish
# 工程根路径
rootPath: ${allRootPaht}/service-rtc
# 包名基础路径
packageBaseFilePath: ${rootPath}/src/main/java/com/starbuds/server/service/${model}
# api-manage 根目录
managePath: ${allRootPaht}/api-manage/src/main/java/com/starbuds/server/api/manage
# api-manage 包名前缀
managePkgPrefix: com.starbuds.server.api.manage

# 模板基础路径
templatesBasePath: xy/${model}

# Mybatis XML 文件路径
mapperXmlBasePath: ${rootPath}/src/main/resources/mapper/