# Mybatis Mapper 文件配置信息
# 包名
packageName: ${managePkgPrefix}.common.service.admin.dao

# 类存储位置
filePath: ${managePath}/common/service/admin/dao/

# 类名后缀；不填写默认为空；生成后类名后缀与填写的一致
suffix: DAO

# 模板文件路径
templates: ${templatesBasePath}/manage_mapper.ftl