# 配置信息
# 包名
packageName: ${managePkgPrefix}.v1.facade

# 类存储位置
filePath: ${managePath}/v1/facade/

# 类名后缀；不填写默认为空；生成后类名后缀与填写的一致
suffix: Facade

# 模板文件路径
templates: ${templatesBasePath}/manage_facade.ftl