# Mybatis Mapper 文件配置信息
# 包名
packageName: ${packagePrefix}.dao

# 类存储位置
filePath: ${packageBaseFilePath}/dao/

# 类名后缀；不填写默认为空；生成后类名后缀与填写的一致
suffix: 4TestDAO

# 模板文件路径
templates: ${templatesBasePath}/mapper_test.ftl