# 配置信息
# 包名
packageName: ${packagePrefix}.pojo.qo

# 类存储位置
filePath: ${packageBaseFilePath}/pojo/qo/

# 类名后缀；不填写默认为空；生成后类名后缀与填写的一致
suffix: PageListQO

# 模板文件路径
templates: ${templatesBasePath}/page_list_qo.ftl