# 配置信息
# 包名
packageName: com.starbuds.server.common.pojo.${model}.qo

# 类存储位置
filePath: ${allRootPaht}/common/src/main/java/com/starbuds/server/common/pojo/${model}/qo/

# 类名后缀；不填写默认为空；生成后类名后缀与填写的一致
suffix: PageListQO

# 模板文件路径
templates: ${templatesBasePath}/page_list_qo.ftl