# 配置信息
# 包名
packageName: com.wazhima.$MODEL_PATH.dao.service

# 类存储位置
filePath: /Users/aoe/IdeaProjects/paqu/wazhima/src/main/java/com/wazhima/$MODEL_PATH/dao/service/

# 类名后缀；不填写默认为空；生成后类名后缀与填写的一致
suffix: POService

# 模板文件路径
templates: xy/wazhima/mapper_service.ftl