# IBaseRule （生成时的）基础规则
# 工程根路径的包名
rootPackageName: com.aoeai.test
# 生成文件的主文件夹路径 必填 必须有结束的"/"
generatorRootPath: xx/
# 主题文件夹名称（例如：resources/themes/base)
themes: base

# IPersistentRule （生成时的）Persistent规则
# PO(持久对象)类所在位置的包名后缀
poPackageName: po
# PO(持久对象)类名后缀；不填写默认为空；生成后类名后缀与填写的一致
poClassNameSuffix: PO
# 生成Java文件时需要过滤掉的表名前缀（,分割）；不填写默认为空
tablePrefixFilter: tb
