# 配置信息
# 包名
packageName: com.wazhima.$MODEL_PATH.web.controller

# 类存储位置
filePath: /Users/aoe/IdeaProjects/paqu/wazhima/src/test/java/com/wazhima/$MODEL_PATH/web/controller/

# 类名后缀；不填写默认为空；生成后类名后缀与填写的一致
suffix: ControllerTest

# 模板文件路径
templates: xy/wazhima1/controller_test.ftl

# 测试主机地址
hostTest: http://localhost:9990/wazhima/