# 配置信息
# 包名
packageName: com.wazhima.$MODEL_PATH.web.request.form

# 类存储位置
filePath: /Users/aoe/IdeaProjects/paqu/wazhima/src/main/java/com/wazhima/$MODEL_PATH/web/request/form/

# 类名后缀；不填写默认为空；生成后类名后缀与填写的一致
suffix: Form

# 模板文件路径
templates: xy/wazhima1/form.ftl